Revert "vndservicemanager: remove static dependency on libselinux"
MAC builds have the following compile error:

Undefined symbols for architecture x86_64:
  "_selabel_file_init", referenced from:
      _initfuncs in label.o
ld: symbol(s) not found for architecture x86_64
clang.real: error: linker command failed with exit code 1 (use -v to see invocation)

Reverting patchset.

This reverts commit 53dfd407ce2729ff5653725a43bdad51e6dd274a.

Change-Id: I8ab4a14ad853a1bf13412a13371661a859a73df7